### ISSUE TITLE
Difficulties encountered when running the example

### ISSUE THREAD

**Issue by YanlinWangWang** [sandialabs/Zoltan#1]
The output does not seem to change after I run the program
Object partition assignments before calling Zoltan
0-----0-----0-----0-----0
|     |     |     |     |
0-----0-----0-----0-----0
|     |     |     |     |
0-----0-----0-----0-----0
|     |     |     |     |
0-----0-----0-----0-----0
|     |     |     |     |
0-----0-----0-----0-----0

Object partition assignments after calling Zoltan
0-----0-----0-----0-----0
|     |     |     |     |
0-----0-----0-----0-----0
|     |     |     |     |
0-----0-----0-----0-----0
|     |     |     |     |
0-----0-----0-----0-----0
|     |     |     |     |
0-----0-----0-----0-----0

**Comment by kddevin** [comment]
Are you running on more than one MPI rank?  Based on the output, I would guess you are running on one MPI rank, in which case all objects are assigned to rank 0 both before and after partitioning.
